### ISSUE TITLE
[RAC] Case Detail: Update header timestamp to show Last updated

### ISSUE THREAD

**Issue by mdefazio** [elastic/stack-design-team#89]
Should this show the open timestamp or the Last updated timestamp?
![image](https://user-images.githubusercontent.com/3756330/129715950-61a53437-8a5a-48cc-a6ab-ce1f31bce613.png)

**Comment by katrin-freihofner** [comment]
I think "last updated" makes more sense. I added this here: https://github.com/elastic/kibana/issues/109822
