### ISSUE TITLE
[RAC] Alerts Management: No way to view selected fields in modal

### ISSUE THREAD

**Issue by mdefazio** [elastic/stack-design-team#97]
When choosing which fields to display, there's no way to determine which ones I've chosen or how many I've chosen.

![image](https://user-images.githubusercontent.com/3756330/129740213-57f30b2f-08ce-484e-9f60-8679df3e56ca.png)

Apologies if this is a duplicate issue as I know we've chatted about this.

**Comment by katrin-freihofner** [comment]
Duplicate of https://github.com/elastic/kibana/issues/108255
